#!/bin/bash

# sudo apt install dmidecode

# Definição de cores
GREEN='\033[0;32m'
BLUE='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NOCOLOR='\033[0m'

sudo clear

echo -e "${YELLOW}Informações da memória RAM:${NOCOLOR}"

sudo dmidecode -t 17 | \
grep -E "Size|Type:|Speed|Serial Number|Part Number|Configured Voltage" | \
grep -vE "Unknown|No Module|None|Volatile" | \
sed 's/^[ \t]*//' | \
sed '/^Size:/i \--------------------------------------------'

# INFORMAÇÕES FIXAS:

echo -e "\n${BLUE}Informações do processador:${NOCOLOR}\n"
lscpu | grep -E "Arquitetura|CPU\(s\)|Nome do modelo|L1d|L1i|L2|L3|Opções" | grep -vE "NUMA"

# INFORMAÇÕES EM TEMPO REAL

echo -e "\n${BLUE}Frequências em tempo real (Pressione Ctrl+C para sair):${NOCOLOR}\n"

# Loop que atualiza apenas a parte das frequências
while true; do
    tput sc
    # Limpa a linha atual e imprime a temperatura
    echo -e "\e[KTemperatura CPU:                  $(sensors | grep -iE 'Tdie|Tctl' | sort | tail -1 | awk '{print $2}')"
    # Imprime os núcleos
    grep "cpu MHz" /proc/cpuinfo | sed 's/cpu MHz/Frequência/' | awk '{print "Núcleo " NR-1 ": " $0 " MHz"}'
    sleep 1
    tput rc
done
