#!/bin/bash

INFO='\033[1;33m'   # Amarelo - para avisos.
NOCOLOR='\033[0m' # Reseta a cor para o padrão do terminal.

echo -e "${INFO}CPU governor in use:${NOCOLOR}"
cpupower frequency-info | grep -E "ondemand|schedutil|performance|userspace"
echo -e "${INFO}CPU governor in use (per thread):${NOCOLOR}"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
