#!/bin/bash

GREEN='\033[0;32m' # Verde
BLUE='\033[0;36m'  # Ciano.
NOCOLOR='\033[0m' # Reseta a cor para o padrão do terminal.

sudo -v
while true; do sudo -v; sleep 60; done &
sudo_pid=$!
trap "kill $sudo_pid" EXIT

echo -e "${BLUE}Atualizando os repositórios do sistema...${NOCOLOR}"
echo
sudo apt update

echo ""
echo -e "${BLUE}Atualizando o sistema...${NOCOLOR}"
echo ""
sudo apt full-upgrade -y

echo ""
echo -e "${BLUE}Limpando o lixo...${NOCOLOR}"
echo ""
sudo apt autoremove -y
sudo apt autoclean -y

echo ""
echo -e "${BLUE}Atualizando os aplicativos em flatpak...${NOCOLOR}"
echo ""
flatpak upgrade -y

echo ""
echo -e "${BLUE}Removendo pacotes e dependências não utilizadas do flatpak...${NOCOLOR}"
echo ""
flatpak uninstall --unused -y

echo ""
echo -e "${BLUE}Atualizando os aplicativos em Snap...${NOCOLOR}"
echo ""
sudo snap refresh

echo ""
echo -e "${GREEN}Script finalizado!${NOCOLOR}"
echo ""
