#!/bin/bash

BLUE='\033[0;36m'  # Ciano.
YELLOW='\033[1;33m'   # Amarelo.
RED='\033[0;31m' # Vermelho.
NOCOLOR='\033[0m' # Reseta a cor para o padrão do terminal.

# Verifica se o primeiro parâmetro ($1) é --sim
if [ "$1" == "--sim" ]; then
    SIMULAR="--dry-run"
    echo -e "${YELLOW}Esse script irá SIMULAR a sincronização da pasta \"Games Settings\" com o Google Drive.${NOCOLOR}"
    echo -e "${YELLOW}Nenhum arquivo no GDrive ou no PC será copiado, apagado ou modificado.${NOCOLOR}"
else
    SIMULAR=""
    echo -e "${YELLOW}Esse script irá sincronizar todos os arquivos da pasta \"Games Settings\" com o Google Drive.${NOCOLOR}"
    echo -e "${RED}Essa operação irá espelhar a pasta \"Games Settings\" do PC no GDrive e não o contrário.${NOCOLOR}"
    echo -e "${RED}Arquivos no GDrive que não estão no PC serão APAGADOS!${NOCOLOR}"
fi


echo -e "${YELLOW}Pressione ENTER para continuar ou CTRL+C para cancelar.${NOCOLOR}"
read

echo -e "${BLUE}Iniciando a sincronização...${NOCOLOR}"

rclone sync "/mnt/Dados (Linux)/Usuários/jedifonseca/Imagens (Arquivo)/Games Settings/" "gdrive,root_folder_id=17Yl123q06dylcEqHFwIep7lKLa_f94-A:" $SIMULAR -P

echo -e "${BLUE}Sincronização finalizada.${NOCOLOR}"

