#!/bin/bash

GREEN='\033[0;32m' # Verde
BLUE='\033[0;36m'  # Ciano.
YELLOW='\033[1;33m'   # Amarelo.
RED='\033[0;31m' # Vermelho.
NOCOLOR='\033[0m' # Reseta a cor para o padrão do terminal.

# Definição de variáveis.
LOCAL="/mnt/Músicas/Minhas Músicas/"
REMOTE="gdrive"
ID="1WaU8_MxTIr3Y9O3ie43NzbfTXi6fKWLo"

###########################################
### CHECAGEM POR PARÂMETROS DE EXECUÇÃO ###
###########################################

# Verifica se o primeiro parâmetro ($1) é --sim
if [ "$1" == "--sim" ]; then
    SIMULAR="--dry-run"
    echo -e "${YELLOW}Esse script irá SIMULAR a sincronização da pasta \"$LOCAL\" com o Google Drive.${NOCOLOR}"
    echo -e "${YELLOW}Nenhum arquivo no GDrive ou no PC será copiado, apagado ou modificado.${NOCOLOR}"
else
    SIMULAR=""
    echo -e "${YELLOW}Esse script irá sincronizar todos os arquivos da pasta \"$LOCAL\" com o Google Drive.${NOCOLOR}"
    echo -e "${RED}Essa operação irá espelhar a pasta do PC no GDrive e não o contrário.${NOCOLOR}"
    echo -e "${RED}Arquivos no GDrive que não estão no PC serão APAGADOS!${NOCOLOR}"
fi

#############################
### FASE DE SINCRONIZAÇÃO ###
#############################

echo -e "${YELLOW}Pressione ENTER para continuar ou CTRL+C para cancelar.${NOCOLOR}"
read

echo -e "${GREEN}Iniciando a sincronização...${NOCOLOR}"

rclone sync "$LOCAL" "$REMOTE,root_folder_id=$ID:" $SIMULAR -P

echo -e "${GREEN}Sincronização finalizada.${NOCOLOR}"

