#!/bin/bash

coloryellow='\033[1;33m'
nocolor='\033[0m'

clear
echo -e "${coloryellow}Esses são os scripts presentes em \"$HOME/.local/bin\".${nocolor}"
cd $HOME/.local/bin
find . -maxdepth 1 -type f -printf "%P\n"
