#!/bin/bash

# Definição de cores.
GREEN='\033[0;32m' # Verde
BLUE='\033[0;36m'  # Ciano.
YELLOW='\033[1;33m'   # Amarelo.
RED='\033[0;31m' # Vermelho.
NOCOLOR='\033[0m' # Reseta a cor para o padrão do terminal.

#################################################
### ENTRADA DE DADOS E DEFINIÇÃO DE VARIÁVEIS ###
#################################################

# Entrada de dados interativa.
# O loop vai rodar enquanto qualquer uma das variáveis estiver vazia.
while [ -z "$LOCAL" -o -z "$REMOTE" ]; do

    echo -e "${RED}--- Entrada de Dados (Campos Obrigatórios) ---${NOCOLOR}"
    echo ""
    echo -e "${YELLOW}AVISO:${NOCOLOR} Se houver uma \"/\" no final do caminho da pasta de origem,"
    echo -e "o rsync irá copiar apenas o conteúdo da mesma e não a própria pasta."
    read -r -p "Caminho da pasta de origem: " LOCAL
    read -r -p "Caminho da pasta de destino: " REMOTE

    if [ -z "$LOCAL" -o -z "$REMOTE" ]; then
        echo -e "\n${RED}ERRO: Todos os campos precisam ser preenchidos!${NOCOLOR}\n"
        # Limpa as variáveis para garantir que o loop pergunte tudo de novo.
        LOCAL=""
        REMOTE=""
    fi
done

# Feedback para o usuário sobre as variáveis que foram definidas.
echo -e "\n${GREEN}Variáveis definidas com sucesso!${NOCOLOR}\n"
echo -e "Pasta de origem:${YELLOW} $LOCAL${NOCOLOR}."
echo -e "Pasta de destino:${YELLOW} $REMOTE${NOCOLOR}."

echo ""
echo -e -n "${YELLOW}Pressione ENTER para continuar ou CTRL+C para cancelar.${NOCOLOR}"
read

##################################
### SINCRONIZAÇÃO DOS ARQUIVOS ###
##################################

# Verifica se as pasta de destino existe.
if [ ! -d "$LOCAL" ]; then
    echo -e "${RED}Erro: A pasta de origem não foi encontrada.${NOCOLOR}"
    exit 1
fi
if [ ! -d "$REMOTE" ]; then
    echo -e "${RED}Erro: A pasta de destino não foi encontrada.${NOCOLOR}"
    exit 1
fi

# Executa o rsync de acordo com o argumento selecionado.
case "$1" in
    "--dry-run")

        rsync -ain --delete --stats --modify-window=1 "$LOCAL" "$REMOTE"
        echo -e "${GREEN}Simulação finalizada. Nenhum arquivo ou pasta foi apagado ou modificado.${NOCOLOR}"

    ;;

    *)

        rsync -ai --delete --stats --modify-window=1 "$LOCAL" "$REMOTE"
        echo -e "${GREEN}Sincronização finalizada!${NOCOLOR}"

    ;;
esac
